version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/fastapi_db
    ports:
      - "8000:8000"

  db:
    image: postgres:15-alpine
    container_name: fastapi_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
