services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: fastapi_app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/fastapi_db
    depends_on:
      db:
        condition: service_started
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./AI:/app/AI
      - ./backend:/app/src

  db:
    image: postgres:15-alpine
    container_name: fastapi_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_db
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
