# docker/Dockerfile.backend
FROM python:3.12-slim

RUN pip install --no-cache-dir uv

WORKDIR /app

# pliki konfiguracyjne projektu
COPY pyproject.toml uv.lock ./

# instalacja zależności do .venv
RUN uv sync --frozen

# kod aplikacji
COPY backend/app ./app

# udostępniamy .venv w $PATH
ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8000

# init_db + serwer
CMD ["sh", "-c", "python -m app.db.init_db && exec uvicorn app.main:app --host 0.0.0.0 --port 8000"]
